/* golden_scenario.h — the shared anti-regression fixture for the ISR-budget work.
 *
 * WHY THIS EXISTS.  The 2026-08 budget work rewrites the interior of
 * engine_process_multi() (hoisting, kernel inlining, a block API, a CCM window
 * cache).  Every one of those is supposed to be a pure SPEED change: the audio
 * that comes out must not move by one bit.  Years of field fixes live in that
 * function — the unity pole-drift, the loop splice + guard samples, the
 * transport declick, the overdub write limiter — and each of them was expensive
 * to find.  A scripted, deterministic run that exercises all of them at once is
 * the cheapest way to notice that one of them has been quietly broken.
 *
 * The scenario drives ~200k samples through every transport state and every
 * feature that costs ISR budget:
 *
 *   phase 0   WRITE, time multiplier sweeping           (moving taps, Hermite)
 *   phase 1   RECIRC + varispeed sweep                  (window map, fractional head)
 *   phase 2   WRITE + delay-time FM + 12-bit crush      (per-tap FM slew, dither)
 *   phase 3   RECIRC + overdub held + varispeed         (multi-write, limiter)
 *   phase 4   RECIRC after a re-splice, then back to WRITE (seam blend)
 *
 * DETERMINISM.  The excitation is generated by INTEGER arithmetic only (an LCG
 * plus a triangle), never libm: sin() is not bit-identical across libms, and a
 * float recurrence is not identical across hosts either once the compiler is
 * free to contract a*b+c into an FMA (default -ffp-contract=fast; aarch64 hosts
 * do, x86-64 hosts do not).  The engine's own arithmetic is still subject to
 * that, which is why the committed assertions are ENERGY FINGERPRINTS with a
 * relative tolerance rather than a bit hash — see test_golden.c.  The bit hash
 * is computed and printed too: it is exact within one host, which is what makes
 * it useful as "did my refactor change anything?" during development.
 */
#ifndef GOLDEN_SCENARIO_H
#define GOLDEN_SCENARIO_H

#include "engine.h"
#include <stdint.h>

#define GS_LEN     131072u      /* delay buffer samples (wraps several times)   */
#define GS_SAMPLES 200000u      /* total frames driven                          */
#define GS_PHASES  5
#define GS_CTL_GRID 64u         /* frames per TIME-control value (see gs_run)   */

/* ---- deterministic excitation (integer only; see DETERMINISM above) -------- */
typedef struct { uint32_t lcg; uint32_t tri; } gs_src_t;

static inline void gs_src_init(gs_src_t *s) { s->lcg = 0x13579BDFu; s->tri = 0u; }

static inline float gs_next(gs_src_t *s)
{
    /* LCG noise, exactly representable: top 16 bits -> [-0.5, 0.5) in 1/65536
     * steps, so the value is a dyadic rational and identical on every host. */
    s->lcg = s->lcg * 1664525u + 1013904223u;
    int32_t n = (int32_t)(s->lcg >> 16) - 32768;       /* -32768..32767        */
    /* triangle at ~1/97 of the rate: a tonal component so the delay taps comb
     * audibly (noise alone hides tap-position bugs in the fingerprint). */
    s->tri = (s->tri + 1u) % 194u;
    int32_t t = (s->tri < 97u) ? (int32_t)s->tri * 674 - 32768
                               : 32768 - (int32_t)(s->tri - 97u) * 674;
    return ((float)n * 0.35f + (float)t * 0.55f) * (1.0f / 32768.0f);
}

/* ---- accumulator: tolerant fingerprint + exact bit hash ------------------- */
typedef struct {
    double  energy;      /* sum x^2 over all channels                          */
    double  absum;       /* sum |x|                                            */
    double  moment;      /* sum (i mod 1024)*x  — catches timing shifts        */
    double  peak;
    uint64_t hash;       /* FNV-1a over the raw float bits (exact, host-local) */
    uint32_t n;
} gs_acc_t;

static inline void gs_acc_init(gs_acc_t *a)
{
    a->energy = a->absum = a->moment = a->peak = 0.0;
    a->hash = 1469598103934665603ull;
    a->n = 0;
}

static inline void gs_acc_push(gs_acc_t *a, const float *chan, unsigned nch)
{
    for (unsigned i = 0; i < nch; i++) {
        float v = chan[i];
        double d = (double)v;
        a->energy += d * d;
        a->absum  += (d < 0.0) ? -d : d;
        a->moment += (double)(a->n & 1023u) * d;
        if (d > a->peak) a->peak = d;
        else if (-d > a->peak) a->peak = -d;
        uint32_t bits;
        __builtin_memcpy(&bits, &v, sizeof bits);
        if (bits == 0x80000000u) bits = 0u;    /* -0.0 == 0.0 for hashing */
        a->hash = (a->hash ^ (uint64_t)bits) * 1099511628211ull;
        a->n++;
    }
}

/* ---- the scripted run ----------------------------------------------------- */
/* Drive the whole scenario. `step` is called with (e, frame, chan) already
 * filled — it is how the caller chooses the per-frame vs the block path.
 *
 * The callback takes a batch: `run` hands it up to `nmax` frames of input and
 * the matching per-frame FM values, and expects `nmax` frames of channel output
 * back.  Feeding the SAME batch boundaries to a per-frame driver and to
 * engine_process_block() is exactly the equivalence we need to prove. */
typedef void (*gs_driver_t)(engine_t *e, const float *in, float time_raw01,
                            const float *fm, float (*chan)[NUM_TAPS], unsigned n,
                            void *user);

/* Per-phase fingerprints are accumulated into acc[0..GS_PHASES-1]; acc[GS_PHASES]
 * gets the total.  `batch` is the number of frames handed to the driver at once
 * (1 = the per-sample path; 16/32 = the block path). */
static void gs_run(engine_t *e, float *buf, gs_driver_t drv, void *user,
                   unsigned batch, gs_acc_t acc[GS_PHASES + 1])
{
    gs_src_t src; gs_src_init(&src);
    float  inb[64];
    float  fmb[64];
    float  chb[64][NUM_TAPS];
    if (batch < 1u) batch = 1u;
    if (batch > 64u) batch = 64u;

    engine_init(e, buf, GS_LEN, /*base*/ 6000.0f, /*lo*/ 0.4f, /*hi*/ 1.6f,
                /*slew*/ 0.01f);
    e->interp = DL_INTERP_HERMITE;
    e->varispeed = 1;
    for (unsigned i = 0; i <= GS_PHASES; i++) gs_acc_init(&acc[i]);

    /* Transport/feature events land BETWEEN blocks on the real thing (they come
     * from the superloop, which cannot preempt the audio ISR), so the batch is
     * clipped at each event frame.  That also makes every batch size see the
     * same events at the same frames, which is what makes the block run and the
     * per-frame run comparable at all. */
    static const unsigned ev[] = { 40000u, 80000u, 120000u, 160000u, 190016u };
    unsigned phase = 0;
    for (unsigned n = 0; n < GS_SAMPLES; ) {
        unsigned bn = batch;
        if (n + bn > GS_SAMPLES) bn = GS_SAMPLES - n;
        for (unsigned i = 0; i < sizeof ev / sizeof ev[0]; i++)
            if (ev[i] > n && ev[i] < n + bn) bn = ev[i] - n;
        /* The TIME control is one scalar for the whole block (main.c latches
         * g_time_raw01 once per ISR call), so it can only step on a grid that
         * every batch size respects — clip there too, or a 1-frame run and a
         * 32-frame run are simply driving different controls. */
        if ((n % GS_CTL_GRID) + bn > GS_CTL_GRID) bn = GS_CTL_GRID - (n % GS_CTL_GRID);

        switch (n) {
        case 40000u:                       /* capture a 20000-sample loop      */
            engine_recirc_window(e, 20000u);
            break;
        case 80000u:                       /* back to WRITE (seam blend)       */
            engine_write(e);
            e->vintage_bits = 12;          /* bit-crush + dither on            */
            engine_set_bandwidth(e, 96000.0f, 11025.0f);
            break;
        case 120000u:                      /* mark a window and recirc it      */
            engine_recirc_between(e, (e->dl.wpos + GS_LEN - 30016u) % GS_LEN);
            e->od_active = 1;              /* overdub held                     */
            break;
        case 160000u:
            e->od_active = 0;
            engine_resplice(e);            /* chunked re-splice under playback */
            break;
        case 190016u:
            engine_write(e);
            break;
        default: break;
        }
        if      (n <  40000u) phase = 0;
        else if (n <  80000u) phase = 1;
        else if (n < 120000u) phase = 2;
        else if (n < 160000u) phase = 3;
        else                  phase = 4;

        /* time multiplier: a slow triangle over the whole run, so the taps are
         * always slewing (and in RECIRC the varispeed rate is always moving).
         * Quantised to the control grid — one value per block, as on hardware. */
        float t01;
        {
            unsigned q = (n / GS_CTL_GRID) * GS_CTL_GRID;
            unsigned p = q % 40000u;
            t01 = (p < 20000u) ? (float)p * (1.0f / 20000.0f)
                               : 1.0f - (float)(p - 20000u) * (1.0f / 20000.0f);
        }

        for (unsigned k = 0; k < bn; k++) {
            inb[k] = gs_next(&src);
            /* delay-time FM: off except phases 2 and 4, where it is a PER-FRAME
             * ramp — it is audio off codec slot 2, and the per-tap slew limiter
             * plus the exact-zero gate only get exercised if it actually moves
             * inside the block. */
            fmb[k] = 0.0f;
            if (phase == 2 || phase == 4) {
                unsigned p = (n + k) % 4096u;
                fmb[k] = ((p < 2048u) ? (float)p : (float)(4096u - p))
                         * (0.15f / 2048.0f);
            }
        }
        drv(e, inb, t01, fmb, chb, bn, user);
        for (unsigned k = 0; k < bn; k++) {
            gs_acc_push(&acc[phase], chb[k], NUM_TAPS);
            gs_acc_push(&acc[GS_PHASES], chb[k], NUM_TAPS);
        }
        n += bn;
    }
}

/* FNV-1a over the final buffer contents (the recorded material: catches splice,
 * overdub-write and write-seam regressions that the output stream might miss). */
static uint64_t gs_buf_hash(const float *buf, uint32_t len)
{
    uint64_t h = 1469598103934665603ull;
    for (uint32_t i = 0; i < len; i++) {
        uint32_t bits; float v = buf[i];
        __builtin_memcpy(&bits, &v, sizeof bits);
        if (bits == 0x80000000u) bits = 0u;
        h = (h ^ (uint64_t)bits) * 1099511628211ull;
    }
    return h;
}

#endif /* GOLDEN_SCENARIO_H */
