/* board.h — 288r hardware constants, ALL in one place.
 *
 * This is the quarantine file for board-specific numbers. Anything tagged
 * [BENCH] is a best-effort value that must be confirmed on the SWD/logic-analyzer
 * session before the image is trusted to make sound (see docs/bench-bringup.md).
 * Everything NOT tagged [BENCH] is confirmed from the RE + bench session 1
 * (re/notes/hardware.md, bench-session-1.md).
 *
 * Confirmed (bench session 1, 2026-07-16):
 *   MCU  STM32F429ZET6, HSE = 8 MHz, SYSCLK 168 / HCLK 168 / APB1 42 / APB2 84.
 *   Codec CS42888 control bus = I2C1.  Audio = SAI1 TDM, 8 slots x 32-bit slot,
 *   24-bit data, 256-bit frame; Block A = Master RX (inputs), Block B = Slave TX
 *   (the 8 DAC channels).  SDRAM = IS42S16400 (8 MB, 16-bit) @ 0xC0000000 (FMC bank 1).
 */
#ifndef BSP_BOARD_H
#define BSP_BOARD_H

/* ---- clock tree (confirmed bench 1) ------------------------------------- */
#define HSE_HZ            8000000u
#define SYSCLK_HZ         168000000u
#define HCLK_HZ           168000000u
#define APB1_HZ           42000000u      /* /4 */
#define APB2_HZ           84000000u      /* /2 */
/* Main PLL: HSE/M *N /P.  M=8 (VCO in 1 MHz), N=336 (VCO 336 MHz), P=2 -> 168. Q=7 (48 MHz USB). */
#define PLL_M             8u
#define PLL_N             336u
#define PLL_P             2u
#define PLL_Q             7u

/* ---- audio -------------------------------------------------------------- */
#define SAMPLE_RATE_HZ    96000u         /* 24/96 (vendor "196KHz" is a typo)     */
#define TDM_SLOTS         8u             /* confirmed: 8 slots                     */
#define TDM_SLOT_BITS     32u            /* confirmed: 32-bit slot                 */
#define TDM_DATA_BITS     24u            /* confirmed: 24-bit data                 */
#define AUDIO_BLOCK_FRAMES 16u           /* DMA half-block size in frames          */

/* SAI kernel clock target: MCLK = 256*Fs = 24.576 MHz for 96 kHz.
 * [BENCH] PLLSAI chain below yields ~24.571 MHz (-0.02%). CONFIRM on the bench
 * whether the codec MCLK is generated by the F429 SAI or by a board oscillator,
 * and retune PLLSAIN/Q + SAI MCKDIV to hit 24.576 MHz exactly. */
#define PLLSAI_N          344u           /* [BENCH] VCO = 1 MHz * 344 = 344 MHz   */
#define PLLSAI_Q          2u             /* [BENCH] 344/2 = 172 MHz               */
#define PLLSAI_DIVQ       7u             /* [BENCH] 172/7 = 24.571 MHz -> SAI_CK  */
#define SAI_MCKDIV        1u             /* [BENCH] SAI_CK/MCKDIV -> MCLK          */

/* ---- SDRAM (IS42S16400, confirmed) -------------------------------------- */
#define SDRAM_BASE        0xD0000000u    /* FMC SDRAM bank 2 (confirmed from stock FMC pins) */
#define SDRAM_BYTES       (8u*1024u*1024u)
/* FMC SDCLK = HCLK/2 = 84 MHz -> 11.9 ns/clk.  Timings from the -7 datasheet
 * (docs/bench-runbook.md), rounded up in SDCLK cycles.  CAS latency 3 (test 2). */
#define SDRAM_CAS_LATENCY 3u             /* [BENCH] try 2 if 3 is unstable        */
#define SDRAM_RPIPE       1u             /* read-pipe delay in HCLK; F429-DISCO uses 1 */
#define SDRAM_REFRESH     636u           /* 7.8125us * 84MHz - 20 ~= 636          */

/* ---- codec CS42888 over I2C1 (confirmed bus; regs [BENCH]) -------------- */
/* 7-bit address set by the AD0/AD1 strap pins. CONFIRMED 0x49 by live I2C scan. */
#define CS42888_I2C_ADDR7 0x49u          /* confirmed on hardware */
#define I2C1_SPEED_HZ     100000u

/* Which ADC TDM slot carries the audio input signal (0..3). [BENCH] live test. */
#define AUDIO_IN_SLOT     0u

/* ---- sens. knob (AUTO CONTROL trigger threshold) — PROVEN slot 1 --------- */
/* OWNER-SWEPT 2026-07-18: with signal playing and every other control static,
 * codec ADC slot 1 rose 0.000 -> 1.000 FS exactly as the sens. knob swept
 * CCW -> CW (and sat at 0.000 for 162 s at full CCW while the signal-in jack
 * was hot — so slot 1 is NOT the signal-in path). The sens knob is an ANALOG
 * attenuator feeding the (pre-gain, inverted) input into slot 1; the auto-
 * trigger + presence LED fire when its envelope crosses the FIXED reference —
 * the knob sets the threshold by analog gain (knob at zero = auto-trigger off,
 * LED dark). NOTE the "signal in" jack/knob path is NOT a codec slot (slots
 * 2..5 stayed at floor with it patched hot) — it reaches the multiplier via
 * the analog Time-CV net ([BENCH]: cv raw pegged 4095 with signal-in hot once,
 * then 0 — patch-state dependent; locate with a knob-wiggle + cv watch). */
#define SENS_IN_SLOT      1
#define SENS_REF          0.02f   /* fixed trigger reference [calibrate on hardware] */
#define ENV_TIME_DEPTH    1.0f    /* envelope->delay-time span in "all sounds" mode:
                                     full-scale sens envelope pushes the multiplier
                                     across its whole range [calibrate by feel]     */
#define SENS_ARM_FRAC     0.4f    /* re-arm hysteresis: env must dip below REF*this  */

/* ---- input-mixer LED (PA0) mode ------------------------------------------ */
/* 1 = whole-chain CLIP indicator (community): lights when the input ADC hits
 *     the 24-bit rail OR any tap output would exceed full scale pre-limiter,
 *     held ~250 ms so single-sample hits are visible.
 * 0 = stock-exact behavior: >0.5 FS level comparator (per-sample PWM). */
#define LED_INPUT_CLIP_MODE  1
#define CLIP_IN_THRESH       0.9999f  /* |input| at/over this = ADC rail       */
#define CLIP_HOLD_BLOCKS     750u     /* ~250 ms at ~3000 blocks/s             */

/* ---- multiplier control source (both OFF for a clean first bring-up) ----- */
/* The multiplier (delay-time / pitch amount) has two possible live sources:
 *   - Time-CV, which arrives on a codec ADC slot in the TDM stream (per-sample,
 *     smooth) — the path you modulate with a CV;
 *   - the multiplier POT on the SPI2 control-surface ADC (per superloop, knob).
 * Enable whichever the bench confirms; leaving both 0 keeps a fixed default delay
 * so the audio path can be validated first. */
#define USE_CV_MULT       0        /* 1 = drive multiplier from a codec CV slot   */
#define MULT_CV_SLOT      1u       /* [BENCH] RX TDM slot carrying Time-CV (1..3)  */
#define CV_MULT_OFFSET    0.0f     /* [BENCH] codec-float value at multiplier=0    */
#define CV_MULT_SCALE     0.5f     /* [BENCH] maps codec float -> [0,1] span       */

#define USE_SPI_MULT      0        /* 1 = drive multiplier from a pot (SPI ADC)   */
#define MULT_POT_CH       0u       /* [BENCH] which SPI-ADC channel is the pot    */
#define POT_MULT_FULLSCALE 4095.0f /* MCP320x 12-bit full scale                    */

/* ---- panel GPIO (confirmed from RE; verify pins on bench) --------------- */
/* cal./pre-set = PB10, SHORT/FULL cycle = PB11, resolution 2-bit = PD11/PD12. */
#define SW_CALPRESET_PORT GPIOB
#define SW_CALPRESET_PIN  10u
#define SW_CYCLE_PORT     GPIOB
#define SW_CYCLE_PIN      11u
#define SW_RES0_PORT      GPIOD
#define SW_RES0_PIN       11u
#define SW_RES1_PORT      GPIOD
#define SW_RES1_PIN       12u

/* ---- config DIP SW1 extra-feature straps (back-panel, near the MCU) ------ */
/* Same 4-position DIP as the resolution bits above: sw3/sw4 = PD11/PD12 (traced),
 * sw1 = x10 delay+looper extend, sw2 = 11025 Hz bandwidth limit. sw1/sw2 pins are
 * NOT yet traced -> [BENCH]. Until confirmed, keep _MAPPED = 0 so the reads compile
 * INERT (feature off) and we never sample an unrelated pin. At the bench: find the
 * two pins, set the port/pin below, and flip _MAPPED to 1. Active-low like the rest.
 * (The port/pin values here are unverified placeholders; they do nothing while
 *  _MAPPED = 0.) */
#define SW_EXTEND_MAPPED     1
#define SW_EXTEND_PORT       GPIOB
#define SW_EXTEND_PIN        10u        /* MEASURED: rear sw1 ON pulls PB10 low
                                           (live IDR capture, bench session 6)    */
#define SW_BANDWIDTH_MAPPED  1
#define SW_BANDWIDTH_PORT    GPIOB
#define SW_BANDWIDTH_PIN     11u        /* rear sw2 (the other f64-read rear pin)  */

/* Owner-confirmed feature behavior. */
#define DELAY_EXTEND_FACTOR  10.0f      /* sw1: x10 delay time + looper length     */
#define BANDWIDTH_LIMIT_HZ   11025.0f   /* sw2: record-path bandwidth limit         */

/* ---- global pitch voice (PITCH_SHIFT.md) — active in pitch mode (bit 4) ---- */
#define PITCH_WINDOW_SAMPLES (0.060f * (float)SAMPLE_RATE_HZ)  /* 60 ms crossfade   */
#define PITCH_BASE_SAMPLES   256.0f     /* base delay offset (~2.7 ms @96k)         */
#define PITCH_RATIO_SLEW     0.0007f    /* one-pole ratio glide/sample: tau ~15 ms.
                                           5 ms exposed control ticks ("steppy");
                                           35 ms lagged the knob ("takes time to
                                           catch up"). ~15 ms tracks a hand sweep
                                           within ~70 ms while burying ticks.    */
#define PITCH_VOICE_GAIN     1.0f       /* wet-leg level of the pitch crossfade on
                                           ch0 (replace semantics — see main.c)  */
/* Time-CV (SPI2 ch0, 12-bit, RESTS AT 0 unpatched — measured) -> volts. */
#define PITCH_CV_CENTER      0.0f
#define PITCH_CV_VOLTS_PER_CODE (5.0f / 4095.0f)

/* Multiplier knob usable ADC span (measured live: full-CCW reads ~644, full-CW
 * ~4094). cal_map01 stretches it to true 0..1 so the whole travel counts. The
 * power-up calibration routine will replace these with per-unit values. */
#define KNOB_ADC_LO          620u
#define KNOB_ADC_HI          4080u

#endif /* BSP_BOARD_H */
