/* board.h — 288r hardware constants, ALL in one place.
 *
 * This is the quarantine file for board-specific numbers. Anything tagged
 * [BENCH] is a best-effort value that must be confirmed on the SWD/logic-analyzer
 * session before the image is trusted to make sound (see docs/bench-bringup.md).
 * Everything NOT tagged [BENCH] is confirmed from the RE + bench session 1
 * (re/notes/hardware.md, bench-session-1.md).
 *
 * Confirmed (bench session 1, 2026-07-16):
 *   MCU  STM32F429ZET6, HSE = 8 MHz, SYSCLK 168 / HCLK 168 / APB1 42 / APB2 84.
 *   Codec CS42888 control bus = I2C1.  Audio = SAI1 TDM, 8 slots x 32-bit slot,
 *   24-bit data, 256-bit frame; Block A = Master RX (inputs), Block B = Slave TX
 *   (the 8 DAC channels).  SDRAM = IS42S16400 (8 MB, 16-bit) @ 0xC0000000 (FMC bank 1).
 */
#ifndef BSP_BOARD_H
#define BSP_BOARD_H

/* ---- clock tree (confirmed bench 1) ------------------------------------- */
#define HSE_HZ            8000000u
#define SYSCLK_HZ         168000000u
#define HCLK_HZ           168000000u
#define APB1_HZ           42000000u      /* /4 */
#define APB2_HZ           84000000u      /* /2 */
/* Main PLL: HSE/M *N /P.  M=8 (VCO in 1 MHz), N=336 (VCO 336 MHz), P=2 -> 168. Q=7 (48 MHz USB). */
#define PLL_M             8u
#define PLL_N             336u
#define PLL_P             2u
#define PLL_Q             7u

/* ---- audio -------------------------------------------------------------- */
#define SAMPLE_RATE_HZ    96000u         /* 24/96 (vendor "196KHz" is a typo)     */
#define TDM_SLOTS         8u             /* confirmed: 8 slots                     */
#define TDM_SLOT_BITS     32u            /* confirmed: 32-bit slot                 */
#define TDM_DATA_BITS     24u            /* confirmed: 24-bit data                 */
#define AUDIO_BLOCK_FRAMES 16u           /* DMA half-block size in frames          */

/* SAI kernel clock target: MCLK = 256*Fs = 24.576 MHz for 96 kHz.
 * [BENCH] PLLSAI chain below yields ~24.571 MHz (-0.02%). CONFIRM on the bench
 * whether the codec MCLK is generated by the F429 SAI or by a board oscillator,
 * and retune PLLSAIN/Q + SAI MCKDIV to hit 24.576 MHz exactly. */
#define PLLSAI_N          344u           /* [BENCH] VCO = 1 MHz * 344 = 344 MHz   */
#define PLLSAI_Q          2u             /* [BENCH] 344/2 = 172 MHz               */
#define PLLSAI_DIVQ       7u             /* [BENCH] 172/7 = 24.571 MHz -> SAI_CK  */
#define SAI_MCKDIV        1u             /* [BENCH] SAI_CK/MCKDIV -> MCLK          */

/* ---- SDRAM (IS42S16400, confirmed) -------------------------------------- */
#define SDRAM_BASE        0xC0000000u    /* FMC SDRAM bank 1. [BENCH] confirm bank */
#define SDRAM_BYTES       (8u*1024u*1024u)
/* FMC SDCLK = HCLK/2 = 84 MHz -> 11.9 ns/clk.  Timings from the -7 datasheet
 * (docs/bench-runbook.md), rounded up in SDCLK cycles.  CAS latency 3 (test 2). */
#define SDRAM_CAS_LATENCY 3u             /* [BENCH] try 2 if 3 is unstable        */
#define SDRAM_REFRESH     636u           /* 7.8125us * 84MHz - 20 ~= 636          */

/* ---- codec CS42888 over I2C1 (confirmed bus; regs [BENCH]) -------------- */
/* 7-bit address set by the AD0/AD1 strap pins: 0x48..0x4B. [BENCH] read the
 * straps / sniff power-up I2C. Default guess 0x48. */
#define CS42888_I2C_ADDR7 0x48u          /* [BENCH]                                */
#define I2C1_SPEED_HZ     100000u

/* Which ADC TDM slot carries the audio input signal (0..3). [BENCH] live test. */
#define AUDIO_IN_SLOT     0u

/* ---- multiplier control source (both OFF for a clean first bring-up) ----- */
/* The multiplier (delay-time / pitch amount) has two possible live sources:
 *   - Time-CV, which arrives on a codec ADC slot in the TDM stream (per-sample,
 *     smooth) — the path you modulate with a CV;
 *   - the multiplier POT on the SPI2 control-surface ADC (per superloop, knob).
 * Enable whichever the bench confirms; leaving both 0 keeps a fixed default delay
 * so the audio path can be validated first. */
#define USE_CV_MULT       0        /* 1 = drive multiplier from a codec CV slot   */
#define MULT_CV_SLOT      1u       /* [BENCH] RX TDM slot carrying Time-CV (1..3)  */
#define CV_MULT_OFFSET    0.0f     /* [BENCH] codec-float value at multiplier=0    */
#define CV_MULT_SCALE     0.5f     /* [BENCH] maps codec float -> [0,1] span       */

#define USE_SPI_MULT      0        /* 1 = drive multiplier from a pot (SPI ADC)   */
#define MULT_POT_CH       0u       /* [BENCH] which SPI-ADC channel is the pot    */
#define POT_MULT_FULLSCALE 4095.0f /* MCP320x 12-bit full scale                    */

/* ---- panel GPIO (confirmed from RE; verify pins on bench) --------------- */
/* cal./pre-set = PB10, SHORT/FULL cycle = PB11, resolution 2-bit = PD11/PD12. */
#define SW_CALPRESET_PORT GPIOB
#define SW_CALPRESET_PIN  10u
#define SW_CYCLE_PORT     GPIOB
#define SW_CYCLE_PIN      11u
#define SW_RES0_PORT      GPIOD
#define SW_RES0_PIN       11u
#define SW_RES1_PORT      GPIOD
#define SW_RES1_PIN       12u

#endif /* BSP_BOARD_H */
