#!/usr/bin/env python3
"""gen_aa_tables.py — polyphase band-limited interpolation tables for the pitch
voice's UP-SHIFT anti-aliasing (see pitch_shift.c ps_read_bl).

Reading the delay buffer faster than it was written (ratio > 1) is decimation:
buffer content above Nyquist/ratio folds into the output. Hermite doesn't band-
limit, so bright material aliases at +1..+2 oct. These tables are Kaiser-windowed
sincs with the cutoff tracking the ratio band, DC-normalized per phase row.

Regenerate with:  python3 tools/gen_aa_tables.py > src/aa_tables.h
Layout: AA_NBANDS bands x (AA_PHASES+1) phase rows x AA_TAPS taps. The +1 row
duplicates phase 0 shifted by one sample so phase interpolation never wraps.
Band edges (ratio): <=1.02 bypass (Hermite), then the AA_BAND_EDGE list.
"""
import numpy as np

TAPS = 16          # FIR length (support [-7..+8] around the read point)
PHASES = 32        # fractional phases per sample step
BETA = 8.0         # Kaiser: ~ -58 dB stopband
# (upper ratio edge, cutoff as fraction of buffer Nyquist) — 0.85 guard band
BANDS = [(1.4, 0.85 / 1.4), (2.0, 0.85 / 2.0), (2.83, 0.85 / 2.83), (4.0, 0.85 / 4.0)]

def kernel(cutoff, frac):
    # Tap j sits at delay (di + CENTER - j); read point at delay (di + frac).
    # Time offset of tap j from the read point: t = j - CENTER + frac
    # (delay decreases toward the present; see ps_read_bl in pitch_shift.c).
    # Kaiser evaluated over the ACTUAL tap span (adversarial-verify finding:
    # sampling a 2*TAPS-wide window left edge taps at 0.33 weight -> fraction-
    # dependent group-delay ripple ~0.17 samples p2p; this cuts it ~10x).
    n = np.arange(TAPS)
    t = n - (TAPS / 2 - 1) + frac
    half = TAPS / 2 + 0.5
    x = np.clip(1.0 - (t / half) ** 2, 0.0, None)
    w = np.i0(BETA * np.sqrt(x)) / np.i0(BETA)
    h = cutoff * np.sinc(cutoff * t) * w
    return h / h.sum()                     # DC gain exactly 1

print("/* aa_tables.h — GENERATED by tools/gen_aa_tables.py; do not hand-edit.")
print(" * Polyphase Kaiser-sinc interpolation tables for up-shift anti-aliasing")
print(f" * ({TAPS} taps, {PHASES} phases + guard row, beta={BETA}; honest stopband")
print(" * ~-30 dB per-row, measured end-to-end alias suppression ~45-50 dB).")
print(" * Band b covers ratio (edge[b-1], edge[b]]; cutoff = 0.85/edge[b]. */")
print("#ifndef AA_TABLES_H")
print("#define AA_TABLES_H")
print(f"#define AA_TAPS   {TAPS}")
print(f"#define AA_PHASES {PHASES}")
print(f"#define AA_NBANDS {len(BANDS)}")
print(f"#define AA_CENTER {TAPS // 2 - 1}   /* integer offset of the kernel center */")
edges = ", ".join(f"{e:.4f}f" for e, _ in BANDS)
print(f"static const float aa_band_edge[AA_NBANDS] = {{ {edges} }};")
print(f"static const float aa_tab[AA_NBANDS][AA_PHASES + 1][AA_TAPS] = {{")
for edge, cut in BANDS:
    print(f"  {{ /* ratio <= {edge}: cutoff {cut:.4f} of buffer Nyquist */")
    for p in range(PHASES + 1):
        h = kernel(cut, p / PHASES)
        row = ", ".join(f"{v: .8e}f" for v in h)
        print(f"    {{ {row} }},")
    print("  },")
print("};")
print("#endif /* AA_TABLES_H */")
